// Generated by CoffeeScript 1.10.0
var component, dom, inject, ref, svg;

ref = require('odojs'), component = ref.component, dom = ref.dom, svg = ref.svg;

inject = require('injectinto');

inject.bind('page:error', component({
  render: function(state, params) {
    return dom('.page--wrapper', [dom('p', params.page.message), dom('p', params.page.details)]);
  }
}));
