// Generated by CoffeeScript 1.10.0
var route;

route = require('odo-route');

route('*', function(p) {
  return {
    status: 404,
    page: {
      id: 'error',
      message: "Sorry, the \"" + p.url + "\" page was not found."
    }
  };
});

module.exports = route;
