// Generated by CoffeeScript 1.10.0
var auth, basic, config;

auth = require('http-auth');

config = require('../config');

basic = auth.basic({
  realm: 'BookIT'
}, function(username, password, cb) {
  return cb(password.toLowerCase() === config.password);
});

module.exports = function(app) {
  return app.use(auth.connect(basic));
};
