// Generated by CoffeeScript 1.10.0
var auth, basic;

auth = require('http-auth');

basic = auth.basic({
  realm: 'BookIT'
}, function(username, password, cb) {
  return cb(password.toLowerCase() === 'sadie');
});

module.exports = function(app) {
  return app.use(auth.connect(basic));
};
