// Generated by CoffeeScript 1.10.0
var hash;

hash = Math.random().toString();

module.exports = function(app) {
  return app.get('/*', function(req, res, next) {
    return res.send("<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge, chrome=1\" />\n    <meta name=\"viewport\" content=\"width=570,user-scalable=no\">\n    <title>BookIT</title>\n    <link rel=\"stylesheet\" href=\"/dist/bundle.css?" + hash + "\" />\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script src=\"/dist/bundle.js?" + hash + "\"></script>\n  </body>\n</html>");
  });
};
