// Generated by CoffeeScript 1.10.0
module.exports = function(app) {
  var express, oneDay, path;
  path = require('path');
  express = require('express');
  oneDay = 1000 * 60 * 60 * 24;
  return app.use('/dist', [
    express["static"](path.join(__dirname, '../', 'dist'), {
      maxAge: oneDay
    })
  ]);
};
