// Generated by CoffeeScript 1.10.0
var chrono, moment, simpledate;

moment = require('moment-timezone');

chrono = require('chronological');

moment = chrono(moment);

simpledate = 'YYYY-MM-DD';

module.exports = function(events) {
  var d, date, day, e, i, id, len, ref, timeline, today;
  timeline = {};
  today = moment().startOf('d');
  for (id in events) {
    e = events[id];
    ref = today.every(1, 'd').between(moment(e.start).add(1, 's'), moment(e.end));
    for (i = 0, len = ref.length; i < len; i++) {
      d = ref[i];
      date = d.format(simpledate);
      if (timeline[date] == null) {
        timeline[date] = {
          count: 0,
          ids: {}
        };
      }
      timeline[date].count += 3;
      timeline[date].ids[id] = true;
    }
    if (timeline[e.start] == null) {
      timeline[e.start] = {
        count: 0,
        ids: {}
      };
    }
    timeline[e.start].count += 1;
    timeline[e.start].ids[id] = true;
    if (timeline[e.end] == null) {
      timeline[e.end] = {
        count: 0,
        ids: {}
      };
    }
    timeline[e.end].count += 2;
    timeline[e.end].ids[id] = true;
  }
  for (d in timeline) {
    day = timeline[d];
    day.isstart = day.count === 1;
    day.isend = day.count === 2;
    day.isduring = day.count >= 3;
    delete day.count;
    day.ids = Object.keys(day.ids);
  }
  return timeline;
};
