// Generated by CoffeeScript 1.10.0
module.exports = ['David & Dale Swap', 'Lewis Swap', 'Stephen & Arlene Swap', 'Simon & Nicola Carter', 'Andrew & Sarah Swap', 'Michael & Sarah Swap', 'Morgan & Kimberley Swap', 'Cameron & Melanie Swap'];
